### ISSUE TITLE
Suspense Data Loading / Avoid useState in useEffect

### ISSUE THREAD

**Issue by snewell92** [jherr/react-native-rscs#1]
Normally I'd probably just open a PR for it, but as this is such a simple example, without having TSQ, unsure if this is even valuable to address in this repo.

It's _quite_ naughty to have that [useState in the useEffect](https://github.com/jherr/react-native-rscs/blob/93c0dc554b2ec7c705da7dc0186e566fdb2a8c99/images-using-rsc/components/images.tsx#L18) and it'd be nice to avoid that common footgun.

Feel free to dismiss this, might be out of scope. There's been recent discussions about this very pattern, but the typical solutions (if my brain is remembering properly) involve libraries or data loading patterns that seem out of scope for this minimal example. I was trying to think how _those_ libraries implement this in the first place, they must either use the suspending throw pattern or perhaps setState in their own internal effects anyway, or have some reducer to coordinate the various states the N/W goes through.

Anyway, I want to write React like this:

```tsx
"use server";
const images = async ({ ...stuff }) => {
  await someStuff();
  return <TheComponent />;
}

"use client"
const useImages = images; // details omitted 🙃 

// This is what I want to see!
const MyUi = () => {
  const images = useImages();
  
  return <>
    {images}
    <button>moar</button>
  </>; 
}

const Page = () => {
  <Suspense fallback="weeee">
    <MyUi />
  </Suspense>
}
```

Just quickly plopping this in after watching the video, will probably come back and heavily edit this.

**Comment by jherr** [comment]
Oh, actually the useEffect can be removed now because of the initial data from the route and the Suspense.

**Comment by snewell92** [comment]
Actually actually this pattern is fine and I look like a buffon. My only saving grace is I suggested TSQ.

Anyway check out how smarter people think about the distinction between "never set state inside a an effect" vs "avoid infinite loops by not synchronously setting state in an effect".

**Comment by snewell92** [comment]
https://bsky.app/profile/jherr.dev/post/3lcb2cf47222t

Forgot the link
